In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
# total number of elements in the tensor
print(x.numel())

# tensor shape
print(x.shape)

12
torch.Size([12])


In [8]:
# change the shape of the tensor to (3,4)
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
# initiate a tensor of zeros with shape (2,3,4)
# this means 2 matrices of shape (3,4), where each matrix has 3 rows and 4 columns
Z = torch.zeros((2, 3, 4))
print(Z)

One = torch.ones((2, 3, 4))
print(One)

rand = torch.rand((2, 3, 4))
print(rand)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0.1784, 0.8566, 0.8827, 0.0504],
         [0.2471, 0.1081, 0.0721, 0.9881],
         [0.6916, 0.9376, 0.3857, 0.1333]],

        [[0.6733, 0.2639, 0.6279, 0.8251],
         [0.5102, 0.7863, 0.6669, 0.1164],
         [0.4239, 0.0264, 0.8660, 0.9093]]])


In [16]:
# construct tensor from data
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
tensor_from_data = torch.tensor(data)
print(tensor_from_data)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [19]:
# indexing and slicing of tensors
print(tensor_from_data[-1]) # last row

print(tensor_from_data[1:3]) # rows from index 1 to 2

#writing elements to tensor
tensor_from_data[0, 0] = 99
print(tensor_from_data)

# assigning multiple elements
tensor_from_data[0:2, :] = 42 # all columns of first two rows
print(tensor_from_data)

tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[99,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])
tensor([[42, 42, 42],
        [42, 42, 42],
        [ 7,  8,  9]])


In [20]:
# Operations on tensors

# exp
print(torch.exp(tensor_from_data))

tensor([[1.7393e+18, 1.7393e+18, 1.7393e+18],
        [1.7393e+18, 1.7393e+18, 1.7393e+18],
        [1.0966e+03, 2.9810e+03, 8.1031e+03]])


In [21]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y, x - y, x * y, x / y, x ** y)

tensor([ 3.,  4.,  6., 10.]) tensor([-1.,  0.,  2.,  6.]) tensor([ 2.,  4.,  8., 16.]) tensor([0.5000, 1.0000, 2.0000, 4.0000]) tensor([ 1.,  4., 16., 64.])


In [24]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(X)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(Y)
op1 = torch.cat((X, Y), dim=0) # concatenate along rows
print(op1)
op2 = torch.cat((X, Y), dim=1) # concatenate along columns
print(op2)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [26]:
# Broadcasting

a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a)
print(b)
print(a + b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
